### ISSUE TITLE
How to run this script in windows 7 and what additional softwares required

### ISSUE THREAD

**Issue by mda-shoeb** [jeysonmc/python-google-speech-scripts#2]
unable to use in Windows 7 and showing the following error

Traceback (most recent call last):
  File "C:\python-google-speech-scripts-master\stt_google.py", line 1, in ?
    import pyaudio
ImportError: No module named pyaudio

**Comment by rcbevans** [comment]
On Windows you need to install the portaudio bindings first http://people.csail.mit.edu/hubert/pyaudio/

**Comment by mda-shoeb** [comment]
Thanks but presenting this error
Traceback (most recent call last):
  File "C:\projects\python-google-speech-scripts-master\stt_google.py", line 101, in <module>
    listen_for_speech()
  File "C:\projects\python-google-speech-scripts-master\stt_google.py", line 43, in listen_for_speech
    data = stream.read(chunk)
  File "C:\Python27\lib\site-packages\pyaudio.py", line 605, in read
    return pa.read_stream(self._stream, num_frames)
KeyboardInterrupt

**Comment by jeysonmc** [comment]
Post the full Traceback. I can't tell what error you're getting.
